version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: pg-importer
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: super-secret
      POSTGRES_DB: people
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d peoples -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
